"use client";

import { FormEvent, useState } from "react";
import { KeyRound, LoaderCircle } from "lucide-react";
export function PasswordChange() {
  const [currentPassword,setCurrent]=useState(""); const [newPassword,setNew]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");if(newPassword!==confirm){setMessage("The new passwords do not match.");return;}setBusy(true);try{const res=await fetch("/api/faisals-room/auth/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const data=await res.json() as {message?:string;error?:string};if(!res.ok)throw new Error(data.error??"Password could not be updated.");setMessage(data.message??"Password updated.");setCurrent("");setNew("");setConfirm("");}catch(e){setMessage(e instanceof Error?e.message:"Password could not be updated.");}finally{setBusy(false);}}
  return <section className="room-card room-password-card"><div><p className="room-eyebrow">Owner security</p><h2>Change password</h2><p>Passwords are hashed with Argon2id. Changing it revokes every active session and creates a fresh session for this device.</p></div><form className="room-password-form" onSubmit={submit}><label htmlFor="current-password">Current password</label><input id="current-password" type="password" autoComplete="current-password" required value={currentPassword} onChange={(e)=>setCurrent(e.target.value)}/><label htmlFor="new-password">New password</label><input id="new-password" type="password" minLength={14} maxLength={256} autoComplete="new-password" required value={newPassword} onChange={(e)=>setNew(e.target.value)}/><small>Use at least 14 characters. A unique passphrase is recommended.</small><label htmlFor="confirm-password">Confirm new password</label><input id="confirm-password" type="password" minLength={14} maxLength={256} autoComplete="new-password" required value={confirm} onChange={(e)=>setConfirm(e.target.value)}/><button className="room-button room-button-primary" type="submit" disabled={busy}>{busy?<LoaderCircle className="room-spin" size={16}/>:<KeyRound size={16}/>} Update password</button><p className="room-editor-message" role="status" aria-live="polite">{message}</p></form></section>;
}
